version: "3.9"
services:
  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: node:16-alpine
    container_name: formulario
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    tty: true
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

    depends_on:
      - "database"
  database:
    container_name: database-form
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formulario
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
